### ISSUE TITLE
 Quagga.decodeSingle is not a function

### ISSUE THREAD

**Issue by sajeetharan** [serratus/quaggaJS#172]
I tried this with Node, and i am stuck with this issue,
```

Quagga.decodeSingle({       ^

TypeError: Quagga.decodeSingle is not a function
    at Object.<anonymous> (E:\pdf-node\test.js:3:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```
My code is as follows,

var Quagga = require('quagga');

```
Quagga.decodeSingle({
    src: "a.jpg",
    numOfWorkers: 0,  // Needs to be 0 when used within node
    inputStream: {
        size: 800  // restrict input-size to be 800px in width (long-side)
    },
    decoder: {
        readers: ["code_128_reader"] // List of active readers
    },
}, function(result) {
    if(result.codeResult) {
        console.log("result", result.codeResult.code);
    } else {
        console.log("not detected");
    }
});
```

**Comment by runn1ng** [comment]
It seems like this library is using ES6 exports and doesn't use `babel-plugin-add-module-exports`.

Either this library has to use this module

https://github.com/59naga/babel-plugin-add-module-exports

or you have to do

`var Quagga = require('quagga').default`

If you use `.default`, it works. (Blame babel6 :rofl: )
