### ISSUE TITLE
Error: SOI not found

### ISSUE THREAD

**Issue by dibishks** [serratus/quaggaJS#373]
Hi, 
I tried to decode an image(https://imgur.com/yaHj392) but it's throwing an error and error is not properly returning in error case to handle the error scenario. 

Can you please check this image link 'https://imgur.com/yaHj392', there is no barcode/qr code in the image, but am expecting it should return the error properly to handle in client side 

```
 Quagga.decodeSingle({
 	src : 'https://imgur.com/yaHj392',
 	numOfWorkers : 0, // Needs to be 0 when used within node
 	inputStream : {
 		size : 800 // restrict input-size to be 800px in width (long-side)
 	},
 	decoder : {
 		readers : ["code_128_reader", "ean_reader", "ean_8_reader", "code_39_reader",
 			"code_39_vin_reader", "codabar_reader", "upc_reader", "upc_e_reader", "i2of5_reader", "2of5_reader", "code_93_reader"]// List of active readers
 	},
 }, function (result) {
 	var barCode = [];
 	console.log('result', result);
 	if (result && result.codeResult) {
 		var formattedOut = [{
 				'points' : [],
 				'format' : '',
 				'code' : result.codeResult.code
 			}
 		];
 		barCode = result.codeResult ? formattedOut : [];
 		console.log('BarCodeExtract 2nd success', barCode);
 	} else {
 		console.log('Not found');
 	}
 });
```
Error: 
Error: SOI not found
    at constructor.parse (/home/dibeesh/koa/pushtest/vision-ocr/node_modules/jpeg-js/lib/decoder.js:598:15)
    at Object.decode (/home/dibeesh/koa/pushtest/vision-ocr/node_modules/jpeg-js/lib/decoder.js:983:11)
    at handleJPEG (/home/dibeesh/koa/pushtest/vision-ocr/node_modules/get-pixels/node-pixels.js:32:21)
    at doParse (/home/dibeesh/koa/pushtest/vision-ocr/node_modules/get-pixels/node-pixels.js:114:7)
    at Request._callback (/home/dibeesh/koa/pushtest/vision-ocr/node_modules/get-pixels/node-pixels.js:177:7)
    at Request.self.callback (/home/dibeesh/koa/pushtest/vision-ocr/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/dibeesh/koa/pushtest/vision-ocr/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/dibeesh/koa/pushtest/vision-ocr/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by ericblade** [comment]
... I don't see anything at all related to Quagga there.  Please explain how you think this is Quagga related?
