### ISSUE TITLE
ReferenceError: exit is not defined

### ISSUE THREAD

**Issue by Underest** [serratus/quaggaJS#504]
Im trying to use quagga in node.js to detect barcodes from png files.
Im giving the decodeSingle() function an uint8array without null bytes as its src. 
```
Quagga.decodeSingle({
            src: uint8array_no_null_bytes,
            numOfWorkers: 0,
            inputStream: {
                size: 800  
            },
            decoder: {
                readers: ["code_128_reader"]
            },
}, function(result) 
        {
            if(result.codeResult) {
                console.log("result", result.codeResult.code);
            } else {
                console.log("not detected");
            }
});     
```

The the following error occurs:
```
.../node_modules/quagga/lib/quagga.js:4251
                exit(1);
                ^

ReferenceError: exit is not defined
    at .../node_modules/quagga/lib/quagga.js:4251:17
    at ReadFileContext.callback (.../node_modules/get-pixels/node-pixels.js:182:9)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:314:13)
```

Can someone explain to me why this error occurs and how to fix it?

**Comment by Underest** [comment]
Was caused by other mistakes.
